name = "gemini-app"
compatibility_date = "2025-08-20"

[env.production]
compatibility_date = "2025-08-20"

# Cloudflare Pages configuration
[build]
command = "npm run build"
cwd = "."
publish = "dist"

# Environment variables for Cloudflare Pages
[vars]
NODE_ENV = "production"

# Build configuration
[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--prefer-offline --no-audit --progress=false"

# SPA routing configuration for Cloudflare Pages
[[redirects]]
from = "/*"
to = "/index.html"
status = 200